version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend_network
    restart: always

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - backend_network
    volumes:
      - mongo_data:/data/db
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - backend_network
    depends_on:
      - redis
      - mongodb
    restart: always

networks:
  backend_network:
    driver: bridge

volumes:
  mongo_data:
